-- CREATING DATABASE 
CREATE DATABASE xyz_company;
USE xyz_company;

-- VIEW ALL DATABASES
SHOW DATABASES;

-- VIEW ALL TABLES A SPECIFIC DATABASE;
SHOW TABLES;

-- CREATING TABLE IN DATABASE
CREATE TABLE employee_info
(
id INT PRIMARY KEY,
emp_name VARCHAR(50) NOT NULL,
salary INT NOT NULL
);

-- VIEW TABLE SCHEMA(STRUCTURE)
DESC employee_info;

-- INSERT DATA IN EMPLOYEE_INFO TABLE
INSERT INTO employee_info VALUES
(1, "mahesh", 45000),
(2, "santhsh", 60000),
(3, "david", 90000);

-- VIEW TABLE DATA 
SELECT * FROM employee_info;
